require("core.plugin_config.treesitter")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.nerdtree")
--require("core.plugin_config.rust_config")
