" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

let g:currentmode={
       \ 'n'  : 'NORMAL  ',
       \ 'v'  : 'VISUAL  ',
       \ 'V'  : 'V·Line  ',
       \ "\<C-V>" : 'V·Block  ',
       \ 'i'  : 'INSERT  ',
       \ 'R'  : 'R  ',
       \ 'Rv' : 'V·Replace  ',
       \ 'c'  : 'Command  ',
       \}
source $VIMRUNTIME/vimrc_example.vim

set langmenu=en_US
let $LANG = 'en_US'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
set hls
set is
set cb=unnamedplus
set gfn=Fixedsys\ Excelsior\ 3.01-L2\ Mono\ 18
set expandtab
set tabstop=4
set shiftwidth=4
set si
set noshowmode
inoremap { {}<Left>
inoremap {<CR> {<CR>}<Esc>O
inoremap {{ {
inoremap {} {}

set undodir=/mnt/hdd/vim_backups/undo
set backupdir=/mnt/hdd/vim_backups/backup
set directory=/mnt/hdd/vim_backups/swp

:lcd %:p:h

set belloff=all
colorscheme zellner

set laststatus=2
set statusline+=\ %{(g:currentmode[mode()])}
set statusline+=%F


:autocmd BufNewFile *.cpp 0r /mnt/hdd/Program-Files/Vim/ClassicTemplate.txt

nnoremap x "_x
vmap x "_d
nnoremap dd "_dd
nnoremap c "_c

noremap s "_ddko

nnoremap <F2> :%y+ <cr>

nnoremap <C-j> :tabprevious <CR>
nnoremap<C-k> :tabnext <CR>
nnoremap <C-x> :tabclose <CR>

set nu
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set rnu
    autocmd BufLeave,FocusLost,InsertEnter * set nornu
	autocmd BufLeave,FocusLost,InsertEnter * set nu
augroup END
